program: scripts/train.py
method: bayes
metric:
  goal: minimize
  name: val_loss
parameters:
  config:
    parameters:
      model:
        parameters:
          keypoint_net_type:
            values:
              - KeypointNet
              - KeypointResnet
            distribution: categorical
          keypoint_loss_weight:
            max: 4
            min: 1
            distribution: uniform
          descriptor_loss_weight:
            max: 4
            min: 1
            distribution: uniform
          score_loss_weight:
            max: 4
            min: 1
            distribution: uniform
          opt_learn_rate:
            max: 0.2
            min: 0.0005
            distribution: uniform
          sched_decay_rate:
            max: 1
            min: 0.1
            distribution: uniform
          epsilon_uv:
            max: 1
            min: 0.3
            distribution: uniform
          do_upsample:
            values:
              - "true"
              - "false"
            distribution: categorical
          use_color:
            values:
              - "true"
              - "false"
            distribution: categorical
          do_cross:
            values:
              - "true"
              - "false"
            distribution: categorical
          with_io:
            values:
              - "true"
              - "false"
            distribution: categorical
