# Copyright 2020 Toyota Research Institute.  All rights reserved.

# Config for training the v0 model:
#    - IONet
#    - descriptor upsampling
#    - cross-border keypoints
#    + descriptor loss

arch:
  accelerator: "cpu"
  fast_dev_run: True # enable debugging

model:
  use_color: False # changed...
  with_io: True # changed...
  do_upsample: False
  do_cross: False
  descriptor_loss: True

datasets:
  batch_size: 4

wandb:
  dry_run: True

datasets:
  rosbags: ["freeRoaming15SonarFels-0805.bag",
            "freeRoaming15SonarFels2-0805.bag", 
            "freeRoaming15Sonar2-0805.bag", 
            "freeRoaming15SonarAuto-0805.bag", 
            "freeRoaming1-0805.bag",
            "freeRoaming15-0805.bag",
            "freeRoaming15Sonar-0805.bag",
            "freeRoaming15SonarFeSteg-0805.bag",
            "freeRoaming45deg-0805.bag",
            "freeRoamingEndGtsam.bag",
            "sonarRecordingFull_gtsam.bag"]  
  n_elevations: 5     
  image_filter_threshold: 0.93  
  image_filter: "gaussian"
  bright_spots_threshold: 210