# Copyright 2020 Toyota Research Institute.  All rights reserved.

# Config for training the v0 model:
#    - IONet
#    - descriptor upsampling
#    - cross-border keypoints
#    + descriptor loss

model:
  use_color: False # changed...
  with_io: True # changed...
  do_upsample: False
  do_cross: False
  descriptor_loss: True

wandb:
  dry_run: True
