# Copyright 2020 Toyota Research Institute.  All rights reserved.

# Config for training the v0 model:
#    - IONet
#    - descriptor upsampling
#    - cross-border keypoints
#    + descriptor loss

arch:
  accelerator: "cpu"
  fast_dev_run: True # enable debugging

model:
  use_color: False # changed...
  with_io: True # changed...
  do_upsample: False
  do_cross: False
  descriptor_loss: True

datasets:
  batch_size: 4

wandb:
  dry_run: True
