# Copyright 2020 Toyota Research Institute.  All rights reserved.

# Config for training the v0 model:
#    - IONet
#    - descriptor upsampling
#    - cross-border keypoints
#    + descriptor loss

arch:
  accelerator: "cpu"
  log_every_n_steps: 5
  max_epochs: 5

model:
  with_io: True # changed...
  do_upsample: False
  do_cross: False
  descriptor_loss: True

datasets:
  batch_size: 4

wandb:
  dry_run: True
  offline: False

datasets:
  rosbags: ["agisoft8.bag"]
  n_elevations: 5     
  image_filter_threshold: 0.95 
  image_filter: "gaussian"
  bright_spots_threshold: 210
  
