name: black

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read black version from requirements.txt
        id: black_version
        run: |
          version=$(cat requirements.txt | grep black | grep -o "[^=]*$")
          echo "BLACK=$version" >> "$GITHUB_OUTPUT"
      - uses: psf/black@stable
        with:
          options: "--config pyproject.toml --check --diff --verbose"
          jupyter: true
          version: "${{ steps.black_version.outputs.BLACK }}"
